# Generated by Django 4.2.1 on 2023-06-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_acercade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acercade',
            name='body',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
