# Generated by Django 4.2.1 on 2023-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0003_equipo_listado_delete_formula1page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='date',
        ),
        migrations.AddField(
            model_name='equipo',
            name='campeonatos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fundacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fundación'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jefe_equipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='motor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='pilotos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
