# Generated by Django 4.2.1 on 2023-06-17 12:08

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_categories'),
        ('formula1', '0006_champcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.blogcategory'),
        ),
    ]
